#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RaviArt")]
	public partial class CompanyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CompanyDataContext() : 
				base(global::Lib.Properties.Settings.Default.RaviArtConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CompanyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CompanyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CompanyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CompanyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Company_Delete")]
		public int Company_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="SmallInt")] System.Nullable<short> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Company_Update")]
		public int Company_Update(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="SmallInt")] System.Nullable<short> id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(128)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShortName", DbType="VarChar(32)")] string shortName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Version", DbType="VarChar(16)")] string version, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(128)")] string address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="VarChar(32)")] string state, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="VarChar(32)")] string country, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pincode", DbType="VarChar(10)")] string pincode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactNo", DbType="VarChar(32)")] string contactNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MobileNo", DbType="VarChar(32)")] string mobileNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(64)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Website", DbType="VarChar(64)")] string website, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GstNo", DbType="VarChar(32)")] string gstNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CinNo", DbType="VarChar(32)")] string cinNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PanNo", DbType="VarChar(32)")] string panNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdharCardNo", DbType="VarChar(32)")] string adharCardNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Jurisdiction", DbType="VarChar(255)")] string jurisdiction, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AuthorisedSing", DbType="VarChar(64)")] string authorisedSing, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillinSystem", DbType="Bit")] System.Nullable<bool> billinSystem, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Branch", DbType="Bit")] System.Nullable<bool> branch, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="SmallInt")] System.Nullable<short> modifiedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, shortName, version, address, state, country, pincode, contactNo, mobileNo, email, website, gstNo, cinNo, panNo, adharCardNo, jurisdiction, authorisedSing, billinSystem, branch, modifiedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Company_Insert")]
		public int Company_Insert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(128)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShortName", DbType="VarChar(32)")] string shortName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Version", DbType="VarChar(16)")] string version, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(128)")] string address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="VarChar(32)")] string state, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="VarChar(32)")] string country, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pincode", DbType="VarChar(10)")] string pincode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactNo", DbType="VarChar(32)")] string contactNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MobileNo", DbType="VarChar(32)")] string mobileNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(64)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Website", DbType="VarChar(64)")] string website, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GstNo", DbType="VarChar(32)")] string gstNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CinNo", DbType="VarChar(32)")] string cinNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PanNo", DbType="VarChar(32)")] string panNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdharCardNo", DbType="VarChar(32)")] string adharCardNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Jurisdiction", DbType="VarChar(255)")] string jurisdiction, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AuthorisedSing", DbType="VarChar(64)")] string authorisedSing, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillinSystem", DbType="Bit")] System.Nullable<bool> billinSystem, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Branch", DbType="Bit")] System.Nullable<bool> branch, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="SmallInt")] System.Nullable<short> modifiedBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="SmallInt")] ref System.Nullable<short> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, shortName, version, address, state, country, pincode, contactNo, mobileNo, email, website, gstNo, cinNo, panNo, adharCardNo, jurisdiction, authorisedSing, billinSystem, branch, modifiedBy, id);
			id = ((System.Nullable<short>)(result.GetParameterValue(20)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Company_SelectAll")]
		public ISingleResult<Company_SelectAllResult> Company_SelectAll([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Branch", DbType="Bit")] System.Nullable<bool> branch)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), branch);
			return ((ISingleResult<Company_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Company_SelectName")]
		public ISingleResult<Company_SelectNameResult> Company_SelectName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="SmallInt")] System.Nullable<short> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Branch", DbType="Bit")] System.Nullable<bool> branch)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, branch);
			return ((ISingleResult<Company_SelectNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Company_SelectOne")]
		public ISingleResult<Company_SelectOneResult> Company_SelectOne([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="SmallInt")] System.Nullable<short> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<Company_SelectOneResult>)(result.ReturnValue));
		}
	}
	
	public partial class Company_SelectAllResult
	{
		
		private short _Id;
		
		private string _Name;
		
		private string _ShortName;
		
		private string _Version;
		
		private string _Address;
		
		private string _State;
		
		private string _Country;
		
		private string _Pincode;
		
		private string _ContactNo;
		
		private string _MobileNo;
		
		private string _Email;
		
		private string _Website;
		
		private string _GstNo;
		
		private string _CinNo;
		
		private string _PanNo;
		
		private string _AdharCardNo;
		
		private string _Jurisdiction;
		
		private string _AuthorisedSing;
		
		private System.Nullable<bool> _BillinSystem;
		
		private bool _Branch;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private System.Nullable<short> _ModifiedBy;
		
		public Company_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="SmallInt NOT NULL")]
		public short Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortName", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this._ShortName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="VarChar(16)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this._Version = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(32)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pincode", DbType="VarChar(10)")]
		public string Pincode
		{
			get
			{
				return this._Pincode;
			}
			set
			{
				if ((this._Pincode != value))
				{
					this._Pincode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNo", DbType="VarChar(32)")]
		public string ContactNo
		{
			get
			{
				return this._ContactNo;
			}
			set
			{
				if ((this._ContactNo != value))
				{
					this._ContactNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="VarChar(32)")]
		public string MobileNo
		{
			get
			{
				return this._MobileNo;
			}
			set
			{
				if ((this._MobileNo != value))
				{
					this._MobileNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(64)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(64)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this._Website = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GstNo", DbType="VarChar(32)")]
		public string GstNo
		{
			get
			{
				return this._GstNo;
			}
			set
			{
				if ((this._GstNo != value))
				{
					this._GstNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CinNo", DbType="VarChar(32)")]
		public string CinNo
		{
			get
			{
				return this._CinNo;
			}
			set
			{
				if ((this._CinNo != value))
				{
					this._CinNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PanNo", DbType="VarChar(32)")]
		public string PanNo
		{
			get
			{
				return this._PanNo;
			}
			set
			{
				if ((this._PanNo != value))
				{
					this._PanNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdharCardNo", DbType="VarChar(32)")]
		public string AdharCardNo
		{
			get
			{
				return this._AdharCardNo;
			}
			set
			{
				if ((this._AdharCardNo != value))
				{
					this._AdharCardNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jurisdiction", DbType="VarChar(255)")]
		public string Jurisdiction
		{
			get
			{
				return this._Jurisdiction;
			}
			set
			{
				if ((this._Jurisdiction != value))
				{
					this._Jurisdiction = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorisedSing", DbType="VarChar(64)")]
		public string AuthorisedSing
		{
			get
			{
				return this._AuthorisedSing;
			}
			set
			{
				if ((this._AuthorisedSing != value))
				{
					this._AuthorisedSing = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillinSystem", DbType="Bit")]
		public System.Nullable<bool> BillinSystem
		{
			get
			{
				return this._BillinSystem;
			}
			set
			{
				if ((this._BillinSystem != value))
				{
					this._BillinSystem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch", DbType="Bit NOT NULL")]
		public bool Branch
		{
			get
			{
				return this._Branch;
			}
			set
			{
				if ((this._Branch != value))
				{
					this._Branch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this._ModifiedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="SmallInt")]
		public System.Nullable<short> ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this._ModifiedBy = value;
				}
			}
		}
	}
	
	public partial class Company_SelectNameResult
	{
		
		private short _Id;
		
		private string _Name;
		
		private string _ShortName;
		
		public Company_SelectNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="SmallInt NOT NULL")]
		public short Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortName", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this._ShortName = value;
				}
			}
		}
	}
	
	public partial class Company_SelectOneResult
	{
		
		private short _Id;
		
		private string _Name;
		
		private string _ShortName;
		
		private string _Version;
		
		private string _Address;
		
		private string _State;
		
		private string _Country;
		
		private string _Pincode;
		
		private string _ContactNo;
		
		private string _MobileNo;
		
		private string _Email;
		
		private string _Website;
		
		private string _GstNo;
		
		private string _CinNo;
		
		private string _PanNo;
		
		private string _AdharCardNo;
		
		private string _Jurisdiction;
		
		private string _AuthorisedSing;
		
		private System.Nullable<bool> _BillinSystem;
		
		private bool _Branch;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private System.Nullable<short> _ModifiedBy;
		
		public Company_SelectOneResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="SmallInt NOT NULL")]
		public short Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortName", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this._ShortName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="VarChar(16)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this._Version = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(32)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pincode", DbType="VarChar(10)")]
		public string Pincode
		{
			get
			{
				return this._Pincode;
			}
			set
			{
				if ((this._Pincode != value))
				{
					this._Pincode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNo", DbType="VarChar(32)")]
		public string ContactNo
		{
			get
			{
				return this._ContactNo;
			}
			set
			{
				if ((this._ContactNo != value))
				{
					this._ContactNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="VarChar(32)")]
		public string MobileNo
		{
			get
			{
				return this._MobileNo;
			}
			set
			{
				if ((this._MobileNo != value))
				{
					this._MobileNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(64)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(64)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this._Website = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GstNo", DbType="VarChar(32)")]
		public string GstNo
		{
			get
			{
				return this._GstNo;
			}
			set
			{
				if ((this._GstNo != value))
				{
					this._GstNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CinNo", DbType="VarChar(32)")]
		public string CinNo
		{
			get
			{
				return this._CinNo;
			}
			set
			{
				if ((this._CinNo != value))
				{
					this._CinNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PanNo", DbType="VarChar(32)")]
		public string PanNo
		{
			get
			{
				return this._PanNo;
			}
			set
			{
				if ((this._PanNo != value))
				{
					this._PanNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdharCardNo", DbType="VarChar(32)")]
		public string AdharCardNo
		{
			get
			{
				return this._AdharCardNo;
			}
			set
			{
				if ((this._AdharCardNo != value))
				{
					this._AdharCardNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jurisdiction", DbType="VarChar(255)")]
		public string Jurisdiction
		{
			get
			{
				return this._Jurisdiction;
			}
			set
			{
				if ((this._Jurisdiction != value))
				{
					this._Jurisdiction = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorisedSing", DbType="VarChar(64)")]
		public string AuthorisedSing
		{
			get
			{
				return this._AuthorisedSing;
			}
			set
			{
				if ((this._AuthorisedSing != value))
				{
					this._AuthorisedSing = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillinSystem", DbType="Bit")]
		public System.Nullable<bool> BillinSystem
		{
			get
			{
				return this._BillinSystem;
			}
			set
			{
				if ((this._BillinSystem != value))
				{
					this._BillinSystem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch", DbType="Bit NOT NULL")]
		public bool Branch
		{
			get
			{
				return this._Branch;
			}
			set
			{
				if ((this._Branch != value))
				{
					this._Branch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this._ModifiedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="SmallInt")]
		public System.Nullable<short> ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this._ModifiedBy = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
